---
label: Site Config
hide_body: true
fields:
- type: text
  name: siteName
  label: Site Name
  config:
    required: true
- type: field_group_list
  name: headerNavigation
  label: Main Navigation
  fields:
  - type: text
    name: text
    label: text
  - type: text
    name: link
    label: link
  - type: boolean
    name: external
    label: external
  config:
    labelField: text
